version: '3.8'
services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - app-network


  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-network


  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network


volumes:
  mongo-data:


networks:
  app-network:
    driver: bridge